### ISSUE TITLE
Error message does not disappear

### ISSUE THREAD

**Issue by stefanengel** [stefanengel/Lumina#2]
If Lumina shows the no network error message, it does not disappear once the network is available again and the next refresh succeeds.

**Comment by dehlen** [comment]
What kind of behavior are you looking for? Currently what I see is, that the error message does not disappear even after a successful refresh (see #3 for example). Because errorMessage is not reset when the request was successful. I am happy to help with a PR to fix this. This problem also occurs for the other error case which could potentially happen. However I'd like to know your opinion on the desired behavior. Should the error message disappear when the next refresh is successful? Or should the error message disappear after x seconds? Or should the error message automatically disappear when network is available again? If the last option is your desired behavior how to handle the other error cases?

Let me know what you think and I am sure I can help with a PR.

**Comment by stefanengel** [comment]
Thanks for your offer. For now I just clear the error message as soon as builds were successfully fetched.
